learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

#nowy
#import django.contrib.auth.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
"""Definiuje wzorzec adresów URL dla learning_log."""

from django.urls import path

from .views import index, topics, topic, new_topic, new_entry, edit_entry

app_name = 'learning_logs'

urlpatterns = [
    #Strona główna
    path('', index, name='index'),
    #Strona tematów
    path('topics/', topics, name='topics'),
    #Strona szczegółowa dotycząca pojedyńczego tematu
    path('topics/<topic_id>', topic, name='topic'),
    #Strona przeznaczona do dodawania nowego tematu
    path('new_topic/', new_topic, name='new_topic'),
    #Strona przeznaczona do dodawania nowego wpisu
    path('new_entry/<topic_id>', new_entry, name='new_entry'),
    #Strona przeznaczona do edycji wpisu
    path('edit_entry/<entry_id>', edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
#from django.contrib.auth import views as auth_views
from django.contrib.auth import login
from . import views

app_name = 'users'

urlpatterns = [
    # Logowanie
    path('', include('django.contrib.auth.urls'), name='login'),
    #path('login/', auth_views.LoginView.as_view(), name='login'),
    # rejestracja
    path('register/', views.register, name='register'),
    #wylogowanie
    path('logout/',views.logout_view, name='logout'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """Temat poznawany przez uzytkownika."""
    text = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Zwraca reprezentację modelu w postaci ciągu tekstowego."""
        return self.text

class Entry(models.Model):
    """Konkretnre inforamcje o postępie w nauce"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Zwraca reprezentuację modelu w postaci ciągu tekstopwego."""
        if len(self.text) >= 50:
            return self.text[:50] + '...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
#from django.http import HttpResponseRedirect #Przekierowanie uzytkownika po dodaniu nowego tematu do strony topic
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """Strona główna aplikacji Learning Log."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Wyświetlenie wszystkich tematów"""
    #Uzytkownik widzi tylko tematy dodane przez siebie
    topics = Topic.objects.filter(owner=request.user).order_by('data_added') 
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Wyświetla pojedyńczy temat i wszystkie powiązane z nim wpisy."""
    topic = Topic.objects.get(id=topic_id)
    #Upewniamy sie, ze temat nalezy do biezacego uzytkownika
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Dodanie nowego tematu"""
    if request.method != 'POST':
        #Nie przekazano zadnych danych, nalezy utworzyc pusty formularz
        form = TopicForm()
    else:
        #Przekazano dane za pomocą zadania POST, nalezy je przetowrzyc
        form = TopicForm(data=request.POST)
    

        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Dodanie nowego wpisu dla określonego tematu."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
            raise Http404

    if request.method != 'POST':
        #Nie przekazano zadnych danych, nalezy utworzyc pusty formularz
        form = EntryForm()
    else: 
        #Przekazano dane za pomocą zadania POST, nalezy je przetowrzyc
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
        
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edycja istniejącego wpisu"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #Żądanie początkowe wypełnienie formularza aktualną treścią wpisu
        form = EntryForm(instance=entry)
    else: 
        #Przekazano dane za pomocą zadania POST, nalezy je przetworzyć 
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect


def logout_view(request):
    """Wylogowanie uzytkownia"""
    logout(request)
    return render(request, 'learning_logs:index')

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.   
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')
           

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>

  <body>
    <!--Statyczny pasek nawigacyjny -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">Tematy<span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text">Hello, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Wyloguj</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Rejestracja</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Zaloguj</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>

  </body>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html'%}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edytuj wpis:</h2>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a>
    </p>

   
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name='submit' class="btn btn-primary">Zapisz zmiany</button>
        {% endbuttons %}
    
    </form>

     
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html'%}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Monitoruj postępy w nauce</h1>
        {% if user.is_authenticated %}
            <p class="lead">Zrób swój własny dziennik nauki i prowadź listę tematów, o których się uczysz. Za 
        każdym razem, gdy dowiesz się czegoś nowego na jakiś temat, zrób wpis podsumowujący to, czego 
        się nauczyłeś.</p>
            <a class="btn btn-primary btn-lg" href="{% url 'learning_logs:new_topic' %}" 
            role="button">Dodaj temat</a>
        {% else %}
            <p class="lead">Zrób swój własny dziennik nauki i prowadź listę tematów, o których się uczysz. Za 
            każdym razem, gdy dowiesz się czegoś nowego na jakiś temat, zrób wpis podsumowujący to, czego 
            się nauczyłeś.</p>

            <a class="btn btn-primary btn-lg" href="{% url 'users:register' %}" 
            role="button">Zarejestruj konto</a>
        {% endif %}
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html'%}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Dodaj nowy wpis:</h2>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a>
    </p>
    <form action="{% url 'learning_logs:new_entry' topic.id%}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form%}
        
        {% buttons %}
            <button name="submit" class="btn btn-primary">Dodaj wpis</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html'%}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Dodaj nowy temat:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form%}
        
        {% buttons %}
            <button name="submit" class="btn btn-primary">Dodaj temat</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html'%}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}



{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Dodaj nowy wpis</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:' d M Y H: i' }}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edytuj wpis</a>
                </small>
            </h4>

            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>
            Nie ma jeszcze zadnego wpisu
        </p>
    {% endfor %}
    </ul>
    

    

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html'%}

{% block page_header %}
    <h2>Tematy:</h2>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>Nie został jeszcze dodany aden temat.</li>
        {% endfor %}
    </ul>

    <h3>
        <a href="{% url 'learning_logs:new_topic' %}">Dodaj temat</a>
    </h3>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}


{% block page_header %}
  <h2>Rejestracja</h2>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">Register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
{% endblock content %}